### ISSUE TITLE
手册内容更新和修订

### ISSUE THREAD

**Issue by highkay** [sgtcloud/sgtcloud-html5-sdk#36]
1.把所有sgt平台相关的文案更新成sgtcloud平台
2.增加根据源码编译（gulp构建）相关的说明
3.因为js没有用到单例，构建实例部分主要侧重于两种方式构造对象
4.创建服务的表述是不正确的（java的说法），js中直接调用即可，请修订一下说法
5.补充一个调用的时序图（补充分服route相关的说明）
6.补充说明每个服务的返回值需要根据jsdoc查询的
7.加入tutorial的相关说明

**Comment by wodog** [comment]
已完成
