### ISSUE TITLE
排行榜教程增加用户注册/登录/创建角色

### ISSUE THREAD

**Issue by Domineer-Long** [sgtcloud/sgtcloud-html5-sdk#39]
排行榜教程增加用户注册/登录/创建角色
1.  手动注册新用户，或一键注册。注册完成的用户名和密码建议保存在localStorage中，下次打开页面自动填入到登录表单中
2.  登录之后显示已有角色，下拉列表形式
3.  没有角色时，可以创建角色
4.  从下拉列表中选择一个角色，并填入分数提交到排行榜

**Comment by wodog** [comment]
已完成     http://sgtcloud.cn/tutorials/
