### ISSUE TITLE
文档上需要补充UserService的quickLogin方法和使用路径

### ISSUE THREAD

**Issue by highkay** [sgtcloud/sgtcloud-html5-sdk#62]
通过quickLogin注册和登录的用户，使用update用户的用户名和密码之后，自动更新本地存储的用户凭据（用户名+密码（需md5）），这个过程是透明的，无需用户介入，但是需要在文档上对这个逻辑进行说明。

**Comment by wodog** [comment]
已添加到使用流程中
https://sgtcloud.gitbooks.io/sgtcloud-html5-sdk/content/useflow/index.html

**Comment by highkay** [comment]
https://sgtcloud.gitbooks.io/sgtcloud-html5-sdk/content/introduction/UserService.html
请参考这个文档的内容
